version: '3'

networks:
  lottery_test_network:

services:
  postgresql:
    image: postgresql:latest
    restart: on-failure
    env_file:
      - ./environments/beta.env
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'
    networks:
      - lottery_test_network
  lottery_application:
    image: amazoncorretto:17.0.10-alpine3.19
    env_file:
      - ./environments/beta.env
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - postgresql
    ports:
      - '8888:8888'
    networks:
      - lottery_test_network
    command: ["./gradlew", "clean", "bootRun"]